### ISSUE TITLE
Bayesian MNIST notebook: kernel dies

### ISSUE THREAD

**Issue by sdcubber** [alpha-i/blog#5]
Hey guys, 

Thanks for the nice notebook on Bayesian deep learning. 

I set up a tensorflow-edward environment and downloaded the notebook. However, the kernel just dies without any error message when I run cell 14:

```
In [14]:
# Create a Pandas DataFrame of posterior samples.
samples_df = pd.DataFrame(data = samples, index=range(n_samples))
# Now create a small subset by taking the first 5 weights, labelled as W_0, ... , W_4.
samples_5 = pd.DataFrame(data = samples_df[list(range(5))].values,columns=["W_0", "W_1", "W_2", "W_3", "W_4"])
# We use Seaborn PairGrid to make a triale plot to show auto and cross correlations.
g = sns.PairGrid(samples_5, diag_sharey=False)
g.map_lower(sns.kdeplot, n_levels = 4,cmap="Blues_d")
g.map_upper(plt.scatter)
g.map_diag(sns.kdeplot,legend=False)
plt.subplots_adjust(top=0.95)
g.fig.suptitle('Joint posterior distribution of the first 5 weights')
```

I'm using the same version of seaborn, matplotlib etc. as you are.

Any idea what might cause this here? Thanks!

**Comment by tbs1980** [comment]
Can you see any error messages on the terminal in which `jupyter notebook` was started?

**Comment by sdcubber** [comment]
This is the only output I get: 

```
[I 15:50:23.825 NotebookApp] Saving file at /notebooks/20170609_MNIST_For_ML_Beginners_The_Bayesian_Way.ipynb
Intel MKL FATAL ERROR: Cannot load libmkl_avx2.so or libmkl_def.so.
[I 15:50:53.620 NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel 1ad5c4e1-2ca8-46f4-bfd8-cfaae6016782 restarted
```

**Comment by tbs1980** [comment]
It looks like your installation of `scipy` does not find the required `MKL` libraries. `seaborn` uses `scipy` to compute kernel density estimation I think. That is where the error comes from. 
Can you check the example below works in your notebook.
https://seaborn.pydata.org/examples/pair_grid_with_kde.html
